### ISSUE TITLE
windows 10 android studio The source and destination cannot both be remote.

### ISSUE THREAD

**Issue by zhanlan123** [skrugly/mirakle#31] opened 2020-03-24 02:46 UTC
![image](https://user-images.githubusercontent.com/7822852/77382957-ad7ab200-6dbc-11ea-9c4a-087e9498fdb8.png)

**Comment by skrugly** [comment] 2020-03-24 06:06
Is your remote machine also running on Windows?

**Comment by kubbens** [comment] 2020-04-17 21:49
I have the same issue.
My local machine is Windows, the remote is Linux

**Comment by skrugly** [comment] 2020-04-21 15:20
I'm looking into this issue right now.
@kubaBabylon could you run your gradle build with `--info` option and post the output here, it would be very helpful.

**Comment by skrugly** [comment] 2020-04-22 17:53
@kubaBabylon @zhanlan123 
Could you guys try out `com.instamotor:mirakle:1.3.3-RC-1` and let me know does it work.

**Comment by kubbens** [comment] 2020-05-01 08:07
@Adambl4 hey sorry I had 0 time.
Will try it tonight :)

**Comment by oqqA** [comment] 2020-06-02 07:34
@Adambl4 Rsync now works but does not find ssh alias
```
> Configure project :
Here's Mirakle 1.3.3-RC-1. All tasks will be executed on lel.

> Task :uploadToRemote
ssh: Could not resolve hostname test_ssh_alias: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

> Task :uploadToRemote FAILED
```

**Comment by oqqA** [comment] 2020-06-02 07:54
@Adambl4 
Wrote path without ssh alias
```
rootProject {
    mirakle {
        host "root@123.123.123.123"
    }
}
```

```
> Configure project :
Here's Mirakle 1.3.3-RC-1. All tasks will be executed on root@123.123.123.123.

> Task :uploadToRemote FAILED
Could not create directory '/home/my_username/.ssh'.
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

But my path on Windows10 is "C:\Users\my_username\\.ssh"

**Comment by skrugly** [comment] 2020-06-02 08:07
@oqqA It looks more like ssh issue connecting to remote machine rather than mirakle issue
The issue is `Host key verification failed.`
Could check this [solution](https://askubuntu.com/questions/45679/ssh-connection-problem-with-host-key-verification-failed-error)

**Comment by oqqA** [comment] 2020-06-02 08:48
@Adambl4 
I manually removed the old key from ".ssh/known_hosts" but issue is repeated
Before and after procedure ssh command in console works and I can use my remote machine

**Comment by w93163red** [comment] 2020-07-18 21:51
I also get the same problem here:
![图片](https://user-images.githubusercontent.com/7308728/87862537-46f74200-c91f-11ea-86c2-a09db1a2eaac.png)

My local is Windows, my remote is Mac

**Comment by skrugly** [comment] 2020-07-20 06:48
@w93163red could you try `com.instamotor:mirakle:1.3.3-RC-2` and let me know does it work or not.

**Comment by w93163red** [comment] 2020-07-20 13:33
@Adambl4 
![图片](https://user-images.githubusercontent.com/7308728/87943422-0527e200-ca6c-11ea-9d49-a14a68588eaa.png)

**Comment by skrugly** [comment] 2020-07-20 19:01
@w93163red seems it was able to connect to remote machine, but there is huge rsync version mismatch. 2.6.9 on remote machine and 3.1.1 on local one.
You need to update rsync on remote [macos machine](https://bayton.org/2018/07/how-to-update-rsync-on-mac-os-high-sierra/).

**Comment by w93163red** [comment] 2020-07-20 20:36
@Adambl4 
The windows version:
![image](https://user-images.githubusercontent.com/7308728/87983871-15a97e00-caa7-11ea-860e-06e6f4ef76bf.png)

The mac version:
![image](https://user-images.githubusercontent.com/7308728/87983902-1e01b900-caa7-11ea-9cc9-507baf4c4559.png)

But I still get:
![image](https://user-images.githubusercontent.com/7308728/87983938-2bb73e80-caa7-11ea-8ba6-68a76ca7ca93.png)

**Comment by skrugly** [comment] 2020-07-21 09:14
@w93163red I believe it still uses older version of rsync on mac when you are conencting to it using ssh.
You can read this [page](https://community.spiceworks.com/topic/2215522-macos-using-old-version-of-rsync-instread-of-new-version), it offers 2 solutins:
1.  Changing the PATH for the local user to put /usr/local/bin/rsync before /usr/bin/rsync.
2. Adding `--rsync-path` to rsync arguments: 
`rsyncToRemoteArgs += ["--rsync-path=/usr/local/bin/rsync"]`

**Comment by w93163red** [comment] 2020-07-21 12:13
The first option cannot work. I have tried. I’ll go ahead and try another
one.

Adambl4 <notifications@github.com>于2020年7月21日 周二05:14写道：

**Comment by w93163red** [comment] 2020-07-21 13:15
For the second option, this is the error message I got

![image](https://user-images.githubusercontent.com/7308728/88059299-a9745c00-cb32-11ea-9ed3-b99e414b4ed0.png)

**Comment by youndie** [comment] 2020-07-22 10:19
Get same issue with builtin windows ssh client. I have changed it to cygwin openssh `--rsh "c:/cygwin64/bin/ssh.exe"`. Sync successfully

**Comment by w93163red** [comment] 2020-07-22 11:28
@youndie may I know how did you change the --rsh?

**Comment by youndie** [comment] 2020-07-23 03:24
@w93163red add sshExecutable config param https://github.com/youndie/mirakle/commit/fc342cee968a09fbdbf03dac8881878635fa6734

**Comment by skrugly** [comment] 2020-07-23 16:08
@w93163red add these lines to mirakle config please and let me know will it able to upload your project to remote machine.
Also make sure this path to cygwin's ssh exists on your local machine.
```
rsyncToRemoteArgs +=["--rsh", "c:/cygwin64/bin/ssh.exe"]
rsyncFromRemoteArgs +=["--rsh", "c:/cygwin64/bin/ssh.exe"]
```

**Comment by skrugly** [comment] 2020-07-23 16:19
@youndie can you explain me why it uses windows built in ssh client in your case? Are you invoking gradle build from PowerShell or from Cygwin environment?

**Comment by youndie** [comment] 2020-07-23 17:16
Run from PowerShell enviroment, "rsync" added to PATH

**Comment by w93163red** [comment] 2020-07-24 15:40
> 
> 
> @w93163red add these lines to mirakle config please and let me know will it able to upload your project to remote machine.
> Also make sure this path to cygwin's ssh exists on your local machine.
> 
> ```
> rsyncToRemoteArgs +=["--rsh", "c:/cygwin64/bin/ssh.exe"]
> rsyncFromRemoteArgs +=["--rsh", "c:/cygwin64/bin/ssh.exe"]
> ```

![图片](https://user-images.githubusercontent.com/7308728/88409129-85b74d00-cda2-11ea-89c6-a526fdcaaa58.png)

**Comment by skrugly** [comment] 2020-07-24 21:03
@w93163red 
This looks promising, just another error: `Host key verification failed`.
Do ssh login to your remote machine from console and accept host key or add this param to `ssh/config`:
```
StrictHostKeyChecking=no 
```

**Comment by skrugly** [comment] 2020-07-25 07:19
> Run from PowerShell enviroment, "rsync" added to PATH

Is it possible to add `cygwin64/bin/ssh.exe` to PATH in order to replace builtin ssh client?

**Comment by skrugly** [comment] 2020-08-13 20:37
Should be fixed. If you are still encounter this reopen the issue.

**Closed as completed by skrugly** 2020-08-13 20:37 UTC

**Comment by artemka13722** [comment] 2020-12-07 15:20
![image](https://user-images.githubusercontent.com/36222432/101368964-5b41d880-38da-11eb-87ba-82247a5b3d4e.png)
