### ISSUE TITLE
Stable error after migrating to Gradle 6.6

### ISSUE THREAD

**Issue by YuriDenison** [skrugly/mirakle#45] opened 2020-08-12 09:42 UTC
> Configure project :
Here's Mirakle 1.3.4. All tasks will be executed on 192.168.0.1.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> standardOutput must not be null

**Comment by smchik** [comment] 2020-08-13 09:25
Same problem. Here are some details

```
> Configure project :
Here's Mirakle 1.3.4. All tasks will be executed on mirakle.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'sample'.
> standardOutput must not be null

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'sample'.
Caused by: java.lang.IllegalStateException: standardOutput must not be null
	at Mirakle$apply$3$1$execute$1.invoke(Mirakle.kt:101)
	at Mirakle$apply$3$1$execute$1.invoke(Mirakle.kt:33)
	at UtilsKt$sam$i$org_gradle_api_Action$0.execute(utils.kt)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:366)
	at Mirakle$apply$3$1.execute(Mirakle.kt:431)
	at Mirakle$apply$3$1.execute(Mirakle.kt:33)

**Comment by skrugly** [comment] 2020-08-13 09:56
Thanks for reporting, I'm fixing this right now

**Comment by skrugly** [comment] 2020-08-13 20:26
Fixed in `com.instamotor:mirakle:1.3.5`

**Closed as completed by skrugly** 2020-08-13 20:26 UTC
